name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        android-sdk-file: android-sdk-tools
    
    - name: Build with Maven
      run: mvn clean package -DskipTests
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: target/*.apk
